### ISSUE TITLE
Testing oddity with rspec-puppet-facts

### ISSUE THREAD

**Issue by genebean** [puppetlabs/puppet_metrics_dashboard#23]
While working on #22 I tried to do the following:

```ruby
require 'spec_helper'
describe 'puppet_metrics_dashboard' do
  on_supported_os.each do |os, facts|
    context "on #{os}" do
      let(:facts) do
        facts.merge(pe_server_version: '2017.2')
      end

      context 'with default values for all parameters' do
        it { is_expected.to compile.with_all_deps }
        it { is_expected.to contain_class('puppet_metrics_dashboard') }
      end
      context 'With an empty array of masters' do
        let(:pre_condition) do
          <<-PRE_COND
            class {'puppet_metrics_dashboard':
              master_list => [],
            }
          PRE_COND
        end

        it { is_expected.to compile.with_all_deps }
      end
    end
  end
end
```

It worked on RHEL 7 but not on the other os's. Below is the test output minus a couple of traces

```
╔ ☕️  gene:~/repos/genebean-puppet_metrics_dashboard (refactor ✘) ✹✭
╚ᐅ pdk bundle exec rspec spec/classes/init_spec.rb
pdk (INFO): Using Ruby 2.5.1
pdk (INFO): Using Puppet 6.0.2

puppet_metrics_dashboard
  on debian-8-x86_64
    with default values for all parameters
      should compile into a catalogue without dependency cycles (FAILED - 1)
      should contain Class[puppet_metrics_dashboard] (FAILED - 2)
    With an empty array of masters
      should compile into a catalogue without dependency cycles (FAILED - 3)
  on ubuntu-16.04-x86_64
    with default values for all parameters
      should compile into a catalogue without dependency cycles (FAILED - 4)
      should contain Class[puppet_metrics_dashboard] (FAILED - 5)
    With an empty array of masters
      should compile into a catalogue without dependency cycles (FAILED - 6)
  on redhat-7-x86_64
    with default values for all parameters
      should compile into a catalogue without dependency cycles
      should contain Class[puppet_metrics_dashboard]
    With an empty array of masters
      should compile into a catalogue without dependency cycles

Failures:

  1) puppet_metrics_dashboard on debian-8-x86_64 with default values for all parameters should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /Users/gene.liverman/repos/genebean-puppet_metrics_dashboard/spec/fixtures/modules/puppet_metrics_dashboard/manifests/repos.pp, line: 34, column: 31) on node gene.liverman-c02r3abag8wp
     # ./spec/classes/init_spec.rb:10:in `block (5 levels) in <top (required)>'

  2) puppet_metrics_dashboard on debian-8-x86_64 with default values for all parameters should contain Class[puppet_metrics_dashboard]
     Failure/Error: contain puppet_metrics_dashboard::repos

     Puppet::PreformattedError:
       Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /Users/gene.liverman/repos/genebean-puppet_metrics_dashboard/spec/fixtures/modules/puppet_metrics_dashboard/manifests/repos.pp, line: 34, column: 31) on node gene.liverman-c02r3abag8wp

  3) puppet_metrics_dashboard on debian-8-x86_64 With an empty array of masters should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /Users/gene.liverman/repos/genebean-puppet_metrics_dashboard/spec/fixtures/modules/puppet_metrics_dashboard/manifests/repos.pp, line: 34, column: 31) on node gene.liverman-c02r3abag8wp
     # ./spec/classes/init_spec.rb:22:in `block (5 levels) in <top (required)>'

  4) puppet_metrics_dashboard on ubuntu-16.04-x86_64 with default values for all parameters should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /Users/gene.liverman/repos/genebean-puppet_metrics_dashboard/spec/fixtures/modules/puppet_metrics_dashboard/manifests/repos.pp, line: 34, column: 31) on node gene.liverman-c02r3abag8wp
     # ./spec/classes/init_spec.rb:10:in `block (5 levels) in <top (required)>'

  5) puppet_metrics_dashboard on ubuntu-16.04-x86_64 with default values for all parameters should contain Class[puppet_metrics_dashboard]
     Failure/Error: contain puppet_metrics_dashboard::repos

     Puppet::PreformattedError:
       Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /Users/gene.liverman/repos/genebean-puppet_metrics_dashboard/spec/fixtures/modules/puppet_metrics_dashboard/manifests/repos.pp, line: 34, column: 31) on node gene.liverman-c02r3abag8wp

  6) puppet_metrics_dashboard on ubuntu-16.04-x86_64 With an empty array of masters should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /Users/gene.liverman/repos/genebean-puppet_metrics_dashboard/spec/fixtures/modules/puppet_metrics_dashboard/manifests/repos.pp, line: 34, column: 31) on node gene.liverman-c02r3abag8wp
     # ./spec/classes/init_spec.rb:22:in `block (5 levels) in <top (required)>'

Finished in 5.91 seconds (files took 5.8 seconds to load)
9 examples, 6 failures

Failed examples:

rspec './spec/classes/init_spec.rb[1:1:1:1]' # puppet_metrics_dashboard on debian-8-x86_64 with default values for all parameters should compile into a cataloguewithout dependency cycles
rspec './spec/classes/init_spec.rb[1:1:1:2]' # puppet_metrics_dashboard on debian-8-x86_64 with default values for all parameters should contain Class[puppet_metrics_dashboard]
rspec './spec/classes/init_spec.rb[1:1:2:1]' # puppet_metrics_dashboard on debian-8-x86_64 With an empty array of masters should compile into a catalogue withoutdependency cycles
rspec './spec/classes/init_spec.rb[1:2:1:1]' # puppet_metrics_dashboard on ubuntu-16.04-x86_64 with default values for all parameters should compile into a catalogue without dependency cycles
rspec './spec/classes/init_spec.rb[1:2:1:2]' # puppet_metrics_dashboard on ubuntu-16.04-x86_64 with default values for all parameters should contain Class[puppet_metrics_dashboard]
rspec './spec/classes/init_spec.rb[1:2:2:1]' # puppet_metrics_dashboard on ubuntu-16.04-x86_64 With an empty array of masters should compile into a catalogue without dependency cycles
```

**Comment by suckatrash** [comment]
I think this because there are RHEL-based os facts defined in `spec/default_facts.yml` that would override rspec-puppet-facts?

**Comment by jarretlavallee** [comment]
It looks like the fact set is missing `$facts['os']['distro']['codename']`

https://github.com/camptocamp/facterdb/blob/master/facts/2.5/ubuntu-16.04-x86_64.facts#L23-L37

Whereas it is included in newer versions of facterdb:

https://github.com/camptocamp/facterdb/blob/master/facts/3.3/ubuntu-16.04-x86_64.facts#L252-L262

What version of facter are you running the test against when this is failing?

**Comment by jarretlavallee** [comment]
We can probably get around this with a custom fact using a confine for the OS.

https://github.com/mcanevet/rspec-puppet-facts#confine-custom-facts

**Comment by genebean** [comment]
That explains so much! I was testing via the version included in #22 which probably means whatever pdk pulled in... I wonder if maybe I needed to clear out my downloaded gems...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jarretlavallee** [comment]
Ok so it looks like we don't ship facter 3 as a gem and so it is going to use 2.5.1. As per https://tickets.puppetlabs.com/browse/FACT-1542, the Facter 3.x gems are being shipped as pre-release.

Maybe we can do something like https://github.com/mcanevet/rspec-puppet-facts/issues/61
