### ISSUE TITLE
Travis Tests are failing

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppet_metrics_dashboard#74]
## Describe the Bug
Without changes to the master branch, the spec tests are timing out after 10 minutes. This seems to be due to a recent gem update. 

## Expected Behavior
The test should complete without issues.

## Steps to Reproduce
1. `bundle install`
2. `bundle exec rake spec`

It will hang and use 100% of the CPU. `parallel_spec` will use multiple and never complete.

## Additional Context

~~~
Resolving deltas: 100% (151/151), done.
I, [2019-08-15T15:23:47.911482 #14561]  INFO -- : Creating symlink from spec/fixtures/modules/puppet_metrics_dashboard to /home/travis/build/puppetlabs/puppet_metrics_dashboard
2 processes for 15 specs, ~ 7 specs per process
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminate
~~~

**Comment by jarretlavallee** [comment]
## Summary
`rspec-puppet-facts` version 1.9.5 has broken the behavior we have in the spec tests. We specify the `facterversion`, which was working with `rspec-puppet-facts` 1.9.2, however, it hangs in 1.9.5.

Each of the spec tests has the following in it, so ensure we are using the 3.7 facts from `facterdb`.

~~~
  on_supported_os(facterversion: '3.7').each do |os, facts|
~~~

This conflicts with a change upstream to use strings instead of symbols for `facterversion`. We can remove the arguments from each spec test and just default to it with the following. 

~~~
RSpec.configure do |c|
  c.default_facter_version = '3.14.0'
end
~~~

## Troubleshooting info

https://github.com/rspec/rspec-rails/issues/1353#issuecomment-93173691 helped identify this.

Adding the following code to the `spec_helper_local.rb` shows the stack trace in reading the facterdb files. 

~~~
puts "rspec pid: #{Process.pid}"

trap 'USR1' do
  threads = Thread.list

  puts
  puts "=" * 80
  puts "Received USR1 signal; printing all #{threads.count} thread backtraces."

  threads.each do |thr|
    description = thr == Thread.main ? "Main thread" : thr.inspect
    puts
    puts "#{description} backtrace: "
    puts thr.backtrace.join("\n")
  end

  puts "=" * 80
end
~~~

Sending a USR1 signal shows the stack trace.

~~~
================================================================================
Received USR1 signal; printing all 1 thread backtraces.

Main thread backtrace: 
/puppet_metrics_dashboard/spec/spec_helper_local.rb:20:in `backtrace'
/puppet_metrics_dashboard/spec/spec_helper_local.rb:20:in `block (2 levels) in <top (required)>'
/puppet_metrics_dashboard/spec/spec_helper_local.rb:16:in `each'
/puppet_metrics_dashboard/spec/spec_helper_local.rb:16:in `block in <top (required)>'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/json_pure-2.1.0/lib/json/common.rb:157:in `parse'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:27:in `jgrep'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/facterdb-0.8.2/lib/facterdb.rb:107:in `get_facts'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/rspec-puppet-facts-1.9.5/lib/rspec-puppet-facts.rb:115:in `block in on_supported_os'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/rspec-puppet-facts-1.9.5/lib/rspec-puppet-facts.rb:107:in `each'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/rspec-puppet-facts-1.9.5/lib/rspec-puppet-facts.rb:107:in `on_supported_os'
/puppet_metrics_dashboard/spec/classes/repos_spec.rb:3:in `block in <top (required)>'
~~~

Another USR1 signal shows the reading.

~~~
================================================================================
Received USR1 signal; printing all 1 thread backtraces.

Main thread backtrace: 
/puppet_metrics_dashboard/spec/spec_helper_local.rb:20:in `backtrace'
/puppet_metrics_dashboard/spec/spec_helper_local.rb:20:in `block (2 levels) in <top (required)>'
/puppet_metrics_dashboard/spec/spec_helper_local.rb:16:in `each'
/puppet_metrics_dashboard/spec/spec_helper_local.rb:16:in `block in <top (required)>'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:127:in `format'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:170:in `has_object?'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:271:in `block in eval_statement'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:265:in `each'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:265:in `eval_statement'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:41:in `block in jgrep'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:39:in `each'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/jgrep-1.5.0/lib/jgrep.rb:39:in `jgrep'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/facterdb-0.8.2/lib/facterdb.rb:107:in `get_facts'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/rspec-puppet-facts-1.9.5/lib/rspec-puppet-facts.rb:115:in `block in on_supported_os'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/rspec-puppet-facts-1.9.5/lib/rspec-puppet-facts.rb:107:in `each'
/puppet_metrics_dashboard/.bundle/ruby/2.5.0/gems/rspec-puppet-facts-1.9.5/lib/rspec-puppet-facts.rb:107:in `on_supported_os'
/puppet_metrics_dashboard/spec/classes/repos_spec.rb:3:in `block in <top (required)>'
~~~
